FROM python:3.12-slim

WORKDIR /opt/docagent

COPY requirements.full.txt .
RUN pip install --no-cache-dir -r requirements.full.txt

COPY frontend ./frontend

ENV PYTHONPATH=/opt/docagent

CMD ["streamlit", "run", "frontend/app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
